import earcut from 'earcut';
import { rgbHex } from './color.mjs';

export function shapesBounds(shapes){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const shape of shapes)for(const[x,y]of shape.points){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}if(!Number.isFinite(minX))return{minX:0,minY:0,maxX:1,maxY:1,width:1,height:1};return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY};}

function targetPoint([x,y],source,target){const nx=(x-source.minX)/Math.max(1e-6,source.width),ny=(y-source.minY)/Math.max(1e-6,source.height),minX=target.minX??-.5,maxX=target.maxX??.5,minY=target.minY??-.5,maxY=target.maxY??.5;return[round(minX+nx*(maxX-minX)),round((target.flipY??true)?maxY-ny*(maxY-minY):minY+ny*(maxY-minY))];}
const round=v=>Math.round(v*10000)/10000;

function shadeFor(fill,base){if(!base)return 0;const values=[fill.r-base.r,fill.g-base.g,fill.b-base.b].sort((a,b)=>a-b);return Math.max(-48,Math.min(48,Math.round(values[1])));}

export function triangulateSemanticShapes(shapes,{target={},roleBaseColors={}}={}){
  const source=shapesBounds(shapes),triangles=[];
  for(const shape of shapes){if(shape.points.length<3)continue;const flat=shape.points.flat(),indices=earcut(flat,null,2),base=roleBaseColors[shape.role];for(let i=0;i<indices.length;i+=3){const points=[shape.points[indices[i]],shape.points[indices[i+1]],shape.points[indices[i+2]]].map(p=>targetPoint(p,source,target));triangles.push({role:shape.role,sourceColor:rgbHex(shape.fill),shade:shadeFor(shape.fill,base),points});}}
  return{sourceBounds:source,targetBounds:{minX:target.minX??-.5,minY:target.minY??-.5,maxX:target.maxX??.5,maxY:target.maxY??.5},triangles};
}

export function emitTypeScript(items,{exportName='AUTO_VECTORIZED_PARTS',sourceLabel='part-vectorizer-v2'}={}){
  const clean=JSON.stringify(items,null,2);return`// Generated by ${sourceLabel}. Do not hand-edit.\nexport const ${exportName} = ${clean} as const;\n`;
}
