import type { CharacterDefinition } from './types';
import {
  ACCENT_OPTIONS, BASE_OPTIONS, BROW_OPTIONS, DEFAULT_CHARACTER, EYE_COLORS, EYE_OPTIONS, FACE_OPTIONS, HAIR_COLORS, HAIR_OPTIONS, HOOD_OPTIONS, JACKET_COLORS, MOUTH_OPTIONS, NOSE_OPTIONS, OUTFIT_OPTIONS, SHIRT_OPTIONS, SKIN_COLORS, STRAP_OPTIONS,
} from '../data/parts';

export type FactoryStyleId='soft'|'cool'|'energetic'|'elegant'|'street'|'futuristic';
export type FactoryLock='face'|'hair'|'outfit'|'colors';
export interface FactoryScores{quality:number;harmony:number;diversity:number;style:number;compatibility:number}
export interface FactoryCandidate{seed:string;style:FactoryStyleId;definition:CharacterDefinition;scores:FactoryScores;signature:string}
export interface FactoryBatchOptions{seed:string|number;style:FactoryStyleId;count?:number;poolSize?:number;anchor?:CharacterDefinition;locks?:readonly FactoryLock[];qualityFloor?:number}

type WeightMap=Readonly<Record<string,number>>;
type Recipe={id:FactoryStyleId;label:string;description:string;hair:WeightMap;face:WeightMap;eyes:WeightMap;brows:WeightMap;outfit:WeightMap;hood:WeightMap;shirt:WeightMap;strap:WeightMap;accent:WeightMap;hairColors:WeightMap;eyeColors:WeightMap;jacketColors:WeightMap;accentColors:readonly string[]};
const w=(preferred:readonly string[],boost=3):WeightMap=>Object.fromEntries(preferred.map(id=>[id,boost]));
const ACCENT_COLORS=['#f1bd42','#f06b47','#56c4d8','#e8578a','#9f7aea','#70c46b','#edf4ff','#ffcf5a'];
export const FACTORY_STYLES:readonly Recipe[]=[
  {id:'soft',label:'SOFT',description:'Friendly rounded shapes and warm colors',hair:w(['bob','wavy','side-tail','bun']),face:w(['soft','oval','round','tapered']),eyes:w(['bright','round','soft','sparkle']),brows:w(['soft','arched','calm','raised']),outfit:w(['hooded','drawstring','short-sleeve']),hood:w(['folded','wide','drawstring']),shirt:w(['tee','tank','three-quarter']),strap:w(['simple','single-pouch']),accent:w(['diamond','chevron','corner']),hairColors:w(['#39281d','#6d3c22','#d77a16','#d95c70']),eyeColors:w(['#5a351b','#9a621f','#873c2f','#7b572f']),jacketColors:w(['#0b5cad','#166f76','#a74343','#3d6d45']),accentColors:['#f1bd42','#f06b47','#70c46b','#ffcf5a']},
  {id:'cool',label:'COOL',description:'Sharper face language with restrained color contrast',hair:w(['long','short-spike','half-up','ponytail']),face:w(['angular','diamond','tapered','long-oval']),eyes:w(['sharp','narrow','determined','side-glance']),brows:w(['straight','angled','bold','flat']),outfit:w(['high-collar','zip-collar','vest']),hood:w(['sharp','high','wing']),shirt:w(['turtleneck','sleeveless-high','long-sleeve']),strap:w(['cross','y-harness','padded']),accent:w(['slash','taper','triangle','point-strip']),hairColors:w(['#2d3540','#173d70','#1a5c91','#39281d']),eyeColors:w(['#24457f','#168a91','#5e646a','#4b2d1f']),jacketColors:w(['#2453a4','#166f76','#7a3d8e']),accentColors:['#56c4d8','#edf4ff','#9f7aea','#f1bd42']},
  {id:'energetic',label:'ENERGETIC',description:'Strong silhouettes, brighter accents and lively expressions',hair:w(['ponytail','twin-tail','side-tail','short-spike']),face:w(['soft','pointed','hex','tapered']),eyes:w(['determined','sparkle','bright','sharp']),brows:w(['angled','raised','bold','arched']),outfit:w(['short-sleeve','hooded','zip-collar']),hood:w(['drawstring','wing','sharp']),shirt:w(['tee','tank','sleeveless-high']),strap:w(['padded','cross','double-pouch']),accent:w(['chevron','triangle','slash','diamond']),hairColors:w(['#a34b1c','#d77a16','#d95c70','#1a5c91']),eyeColors:w(['#9a621f','#873c2f','#24457f','#168a91']),jacketColors:w(['#a74343','#0b5cad','#166f76','#7a3d8e']),accentColors:['#ffcf5a','#f06b47','#56c4d8','#e8578a']},
  {id:'elegant',label:'ELEGANT',description:'Longer proportions and calmer refined pairings',hair:w(['long','wavy','braid','half-up']),face:w(['oval','long-oval','diamond','soft']),eyes:w(['soft','sleepy','side-glance','narrow']),brows:w(['arched','calm','thin','soft']),outfit:w(['high-collar','vest','zip-collar']),hood:w(['high','wide','folded']),shirt:w(['turtleneck','long-sleeve','three-quarter']),strap:w(['simple','single-pouch','y-harness']),accent:w(['long-strip','taper','diamond','corner']),hairColors:w(['#39281d','#4b3021','#2d3540','#6c3f87']),eyeColors:w(['#7b572f','#59662f','#6e3d88','#5e646a']),jacketColors:w(['#2453a4','#7a3d8e','#3d6d45']),accentColors:['#edf4ff','#f1bd42','#9f7aea','#56c4d8']},
  {id:'street',label:'STREET',description:'Layered outfits, harnesses and bold practical color blocking',hair:w(['bob','short-spike','half-up','side-tail']),face:w(['square','hex','angular','round']),eyes:w(['determined','narrow','side-glance','bright']),brows:w(['bold','straight','flat','angled']),outfit:w(['hooded','drawstring','short-sleeve']),hood:w(['drawstring','wide','folded']),shirt:w(['tee','three-quarter','tank']),strap:w(['double-pouch','cross','padded','single-pouch']),accent:w(['slash','chevron','corner','point-strip']),hairColors:w(['#2d3540','#39281d','#a34b1c','#3c884b']),eyeColors:w(['#5a351b','#59662f','#168a91','#5e646a']),jacketColors:w(['#0b5cad','#3d6d45','#a74343','#166f76']),accentColors:['#f06b47','#ffcf5a','#56c4d8','#70c46b']},
  {id:'futuristic',label:'FUTURE',description:'Geometric parts and high-contrast cyber palettes',hair:w(['short-spike','half-up','twin-tail','long']),face:w(['diamond','hex','angular','pointed']),eyes:w(['sharp','narrow','sparkle','side-glance']),brows:w(['angled','bold','straight','raised']),outfit:w(['zip-collar','high-collar','vest']),hood:w(['wing','sharp','high']),shirt:w(['sleeveless-high','turtleneck','tank']),strap:w(['y-harness','cross','double-pouch']),accent:w(['triangle','point-strip','slash','taper']),hairColors:w(['#173d70','#1a5c91','#6c3f87','#d95c70']),eyeColors:w(['#24457f','#168a91','#6e3d88','#5e646a']),jacketColors:w(['#2453a4','#166f76','#7a3d8e']),accentColors:['#56c4d8','#e8578a','#9f7aea','#edf4ff']},
] as const;

const clamp=(value:number,min=0,max=100)=>Math.max(min,Math.min(max,value));
const round=(value:number)=>Math.round(value*10)/10;
const clone=<T>(value:T):T=>structuredClone(value);
const hashSeed=(value:string|number)=>{let h=2166136261>>>0;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
const rngFor=(value:string|number)=>{let a=hashSeed(value)||1;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};};
function weightedPick<T extends string>(items:readonly {id:T}[],weights:WeightMap,rng:()=>number):T{const total=items.reduce((sum,item)=>sum+(weights[item.id]??1),0);let cursor=rng()*total;for(const item of items){cursor-=weights[item.id]??1;if(cursor<=0)return item.id;}return items[items.length-1].id;}
function weightedColor(items:readonly string[],weights:WeightMap,rng:()=>number){return weightedPick(items.map(id=>({id})),weights,rng);}
const recipeFor=(id:FactoryStyleId)=>FACTORY_STYLES.find(recipe=>recipe.id===id)??FACTORY_STYLES[0];
const identity=()=>({x:0,y:0,scaleX:1,scaleY:1,rotation:0,spacing:0});

function colorStats(hex:string){const value=hex.replace('#',''),r=parseInt(value.slice(0,2),16)/255,g=parseInt(value.slice(2,4),16)/255,b=parseInt(value.slice(4,6),16)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h=(h*60+360)%360;}const s=d/(1-Math.abs(2*l-1)||1);return{h,s,l};}
function colorHarmony(c:CharacterDefinition){const jacket=colorStats(c.colors.jacket),accent=colorStats(c.colors.accent),hair=colorStats(c.colors.hair),skin=colorStats(c.colors.skin),deltaHue=Math.min(Math.abs(jacket.h-accent.h),360-Math.abs(jacket.h-accent.h)),contrast=Math.abs(jacket.l-accent.l),hairSkin=Math.abs(hair.l-skin.l);return clamp(66+contrast*32+hairSkin*22+(deltaHue>25?8:0)-(accent.s<.2?6:0));}
const inGroup=(value:string,group:readonly string[])=>group.includes(value);
function facialCompatibility(c:CharacterDefinition){let score=72;if(inGroup(c.faceShape,['round','soft','oval'])&&inGroup(c.eyeStyle,['bright','round','soft','sparkle']))score+=10;if(inGroup(c.faceShape,['angular','diamond','hex','pointed'])&&inGroup(c.eyeStyle,['sharp','narrow','determined','side-glance']))score+=10;if(inGroup(c.eyeStyle,['sharp','narrow','determined'])&&inGroup(c.browStyle,['angled','bold','straight','flat']))score+=10;if(inGroup(c.eyeStyle,['bright','soft','round'])&&inGroup(c.browStyle,['soft','arched','calm','raised']))score+=8;if(c.eyeStyle==='closed'&&c.mouthStyle==='surprised')score-=12;if(c.browStyle==='worried'&&inGroup(c.mouthStyle,['smile-open','wide-open']))score-=7;return clamp(score);}
function silhouetteCompatibility(c:CharacterDefinition){let score=74;if(inGroup(c.faceShape,['round','square'])&&inGroup(c.hairStyle,['long','ponytail','side-tail','half-up']))score+=8;if(inGroup(c.faceShape,['long-oval','pointed'])&&inGroup(c.hairStyle,['bob','bun','twin-tail']))score+=8;if(c.outfitStyle==='vest'&&inGroup(c.shirtStyle,['sleeveless-high','tank']))score+=8;if(inGroup(c.outfitStyle,['high-collar','zip-collar'])&&inGroup(c.hoodStyle,['high','sharp','wing']))score+=7;if(c.outfitStyle==='short-sleeve'&&c.shirtStyle==='long-sleeve')score-=10;if(c.strapStyle==='y-harness'&&inGroup(c.outfitStyle,['vest','zip-collar']))score+=6;if(c.hoodStyle==='wing'&&c.hairStyle==='wavy')score-=5;return clamp(score);}
function styleAffinity(c:CharacterDefinition,recipe:Recipe){const values:[string,WeightMap][]=[[c.hairStyle,recipe.hair],[c.faceShape,recipe.face],[c.eyeStyle,recipe.eyes],[c.browStyle,recipe.brows],[c.outfitStyle,recipe.outfit],[c.hoodStyle,recipe.hood],[c.shirtStyle,recipe.shirt],[c.strapStyle,recipe.strap],[c.accentStyle,recipe.accent],[c.colors.hair,recipe.hairColors],[c.colors.eyes,recipe.eyeColors],[c.colors.jacket,recipe.jacketColors]];const preferred=values.filter(([value,map])=>(map[value]??1)>1).length;return clamp(48+preferred/values.length*52);}
function hardGate(c:CharacterDefinition){const transforms=Object.values(c.transforms);if(transforms.some(t=>Object.values(t).some(value=>typeof value==='number'&&!Number.isFinite(value))))return false;if(c.colors.brows!==c.colors.hair)return false;if(!c.colors.accent.startsWith('#')||!c.colors.skin.startsWith('#'))return false;return true;}
function scoreCandidate(c:CharacterDefinition,recipe:Recipe){const face=facialCompatibility(c),silhouette=silhouetteCompatibility(c),color=colorHarmony(c),compatibility=round((face+silhouette)/2),harmony=round(face*.36+silhouette*.34+color*.30),style=round(styleAffinity(c,recipe)),quality=round(clamp(harmony*.58+compatibility*.22+style*.20));return{quality,harmony,style,compatibility};}

function applyLocks(generated:CharacterDefinition,anchor:CharacterDefinition|undefined,locks:readonly FactoryLock[]){if(!anchor)return generated;const set=new Set(locks);if(set.has('face')){generated.faceShape=anchor.faceShape;generated.eyeStyle=anchor.eyeStyle;generated.browStyle=anchor.browStyle;generated.noseStyle=anchor.noseStyle;generated.mouthStyle=anchor.mouthStyle;generated.transforms=clone(anchor.transforms);}if(set.has('hair'))generated.hairStyle=anchor.hairStyle;if(set.has('outfit')){generated.baseStyle=anchor.baseStyle;generated.outfitStyle=anchor.outfitStyle;generated.hoodStyle=anchor.hoodStyle;generated.shirtStyle=anchor.shirtStyle;generated.strapStyle=anchor.strapStyle;generated.accentStyle=anchor.accentStyle;}if(set.has('colors'))generated.colors=clone(anchor.colors);return generated;}
function createDefinition(seed:string,style:FactoryStyleId,anchor?:CharacterDefinition,locks:readonly FactoryLock[]=[]){const rng=rngFor(seed),recipe=recipeFor(style),c=clone(DEFAULT_CHARACTER);c.baseStyle=weightedPick(BASE_OPTIONS,{},rng);c.outfitStyle=weightedPick(OUTFIT_OPTIONS,recipe.outfit,rng);c.hoodStyle=weightedPick(HOOD_OPTIONS,recipe.hood,rng);c.shirtStyle=weightedPick(SHIRT_OPTIONS,recipe.shirt,rng);c.strapStyle=weightedPick(STRAP_OPTIONS,recipe.strap,rng);c.accentStyle=weightedPick(ACCENT_OPTIONS,recipe.accent,rng);c.hairStyle=weightedPick(HAIR_OPTIONS,recipe.hair,rng);c.faceShape=weightedPick(FACE_OPTIONS,recipe.face,rng);c.eyeStyle=weightedPick(EYE_OPTIONS,recipe.eyes,rng);c.browStyle=weightedPick(BROW_OPTIONS,recipe.brows,rng);c.noseStyle=weightedPick(NOSE_OPTIONS,{},rng);c.mouthStyle=weightedPick(MOUTH_OPTIONS,{},rng);c.colors.skin=weightedColor(SKIN_COLORS,{},rng);c.colors.hair=weightedColor(HAIR_COLORS,recipe.hairColors,rng);c.colors.brows=c.colors.hair;c.colors.eyes=weightedColor(EYE_COLORS,recipe.eyeColors,rng);c.colors.jacket=weightedColor(JACKET_COLORS,recipe.jacketColors,rng);c.colors.accent=recipe.accentColors[Math.floor(rng()*recipe.accentColors.length)]??ACCENT_COLORS[0];c.transforms={eyes:identity(),brows:identity(),nose:identity(),mouth:identity()};return applyLocks(c,anchor,locks);}
export function characterSignature(c:CharacterDefinition){return[c.baseStyle,c.outfitStyle,c.hoodStyle,c.shirtStyle,c.strapStyle,c.accentStyle,c.hairStyle,c.faceShape,c.eyeStyle,c.browStyle,c.noseStyle,c.mouthStyle,c.colors.skin,c.colors.hair,c.colors.eyes,c.colors.jacket,c.colors.accent].join('|');}
function signatureDistance(a:CharacterDefinition,b:CharacterDefinition){const av=characterSignature(a).split('|'),bv=characterSignature(b).split('|');let distance=0,total=0;for(let i=0;i<av.length;i++){const weight=i>=12?0.65:(i===6||i===7||i===8?1.4:1);total+=weight;if(av[i]!==bv[i])distance+=weight;}return total?distance/total:0;}

export function createFactoryCandidate(seed:string|number,style:FactoryStyleId,anchor?:CharacterDefinition,locks:readonly FactoryLock[]=[]):FactoryCandidate|null{const candidateSeed=String(seed),definition=createDefinition(candidateSeed,style,anchor,locks);if(!hardGate(definition))return null;const base=scoreCandidate(definition,recipeFor(style));return{seed:candidateSeed,style,definition,signature:characterSignature(definition),scores:{...base,diversity:100}};}

export function generateFactoryBatch({seed,style,count=12,poolSize=72,anchor,locks=[],qualityFloor=72}:FactoryBatchOptions):FactoryCandidate[]{const safeCount=Math.max(1,Math.min(24,Math.floor(count))),safePool=Math.max(safeCount,Math.min(240,Math.floor(poolSize))),pool:FactoryCandidate[]=[],seen=new Set<string>();for(let i=0;i<safePool;i++){const candidate=createFactoryCandidate(`${seed}:${style}:${i}`,style,anchor,locks);if(!candidate||seen.has(candidate.signature))continue;seen.add(candidate.signature);if(candidate.scores.quality>=qualityFloor)pool.push(candidate);}if(pool.length<safeCount){for(let i=safePool;i<safePool*3&&pool.length<safeCount;i++){const candidate=createFactoryCandidate(`${seed}:${style}:fallback:${i}`,style,anchor,locks);if(!candidate||seen.has(candidate.signature))continue;seen.add(candidate.signature);pool.push(candidate);}}pool.sort((a,b)=>b.scores.quality-a.scores.quality||b.scores.harmony-a.scores.harmony);const selected:FactoryCandidate[]=[];while(pool.length&&selected.length<safeCount){let bestIndex=0,bestRank=-Infinity,bestDiversity=100;for(let i=0;i<pool.length;i++){const candidate=pool[i],diversity=selected.length?Math.min(...selected.map(other=>signatureDistance(candidate.definition,other.definition)))*100:100,rank=candidate.scores.quality*.52+candidate.scores.harmony*.18+candidate.scores.style*.12+diversity*.18;if(rank>bestRank){bestRank=rank;bestIndex=i;bestDiversity=diversity;}}const [picked]=pool.splice(bestIndex,1);picked.scores.diversity=round(bestDiversity);selected.push(picked);}return selected;}

export function createVariationBatch(anchor:CharacterDefinition,options:Omit<FactoryBatchOptions,'anchor'>){return generateFactoryBatch({...options,anchor});}
