import type { AccentStyleId, HairStyleId, PartDefinition, PartTransform, StrapStyleId, Vec2 } from './types';

export interface FitBounds { minX:number; minY:number; maxX:number; maxY:number }
export interface FitRect extends FitBounds {}
export interface AutoFitEntry { id:string; family:string; transform:PartTransform; source:FitBounds; target:FitRect; fitted:FitBounds; score:number }
export interface AutoFitIssue { code:string; family:string; id:string; severity:'warning'|'error'; value:number; limit:number }
export interface AutoFitReport { version:2; entries:AutoFitEntry[]; issues?:AutoFitIssue[]; totalScore?:number }

const IDENTITY:PartTransform={x:0,y:0,scaleX:1,scaleY:1,rotation:0,spacing:0};
const EPS=1e-6;
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const width=(b:FitBounds)=>Math.max(EPS,b.maxX-b.minX);
const height=(b:FitBounds)=>Math.max(EPS,b.maxY-b.minY);
const center=(b:FitBounds):Vec2=>[(b.minX+b.maxX)/2,(b.minY+b.maxY)/2];
const triangleArea=(points:readonly Vec2[])=>Math.abs((points[0][0]*(points[1][1]-points[2][1])+points[1][0]*(points[2][1]-points[0][1])+points[2][0]*(points[0][1]-points[1][1]))*.5);
const quantile=(values:number[],q:number)=>{const sorted=[...values].sort((a,b)=>a-b),index=(sorted.length-1)*q,lo=Math.floor(index),hi=Math.ceil(index);return sorted[lo]*(hi-index)+sorted[hi]*(index-lo);};

export function boundsForPart(def:PartDefinition,predicate?:(layer:string)=>boolean):FitBounds{let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const triangle of def.triangles){if(predicate&&!predicate(triangle.layer))continue;for(const[x,y]of triangle.points){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}}return Number.isFinite(minX)?{minX,minY,maxX,maxY}:{...def.bounds};}
export function coverageBoundsForPart(def:PartDefinition,predicate?:(layer:string)=>boolean,retainArea=.995):FitBounds{const triangles=def.triangles.filter(t=>!predicate||predicate(t.layer)).map(t=>({t,area:triangleArea(t.points)})).filter(x=>x.area>EPS).sort((a,b)=>b.area-a.area);if(!triangles.length)return boundsForPart(def,predicate);const total=triangles.reduce((sum,x)=>sum+x.area,0),wanted=total*clamp(retainArea,.8,1);let accumulated=0,minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const{t,area}of triangles){for(const[x,y]of t.points){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}accumulated+=area;if(accumulated>=wanted)break;}return Number.isFinite(minX)?{minX,minY,maxX,maxY}:boundsForPart(def,predicate);}
function quantileBoundsForPart(def:PartDefinition,predicate:(layer:string)=>boolean,xLow:number,xHigh:number,yLow:number,yHigh:number):FitBounds{const xs:number[]=[],ys:number[]=[];for(const triangle of def.triangles){if(!predicate(triangle.layer))continue;for(const[x,y]of triangle.points){xs.push(x);ys.push(y);}}if(!xs.length)return boundsForPart(def,predicate);return{minX:quantile(xs,xLow),minY:quantile(ys,yLow),maxX:quantile(xs,xHigh),maxY:quantile(ys,yHigh)};}

const featureBoundsCache=new WeakMap<PartDefinition,Map<string,FitBounds>>(),outfitBoundsCache=new WeakMap<PartDefinition,Map<string,FitBounds>>(),faceBoundsCache=new WeakMap<PartDefinition,FitBounds>(),jacketBoundsCache=new WeakMap<PartDefinition,FitBounds>(),jacketTorsoCache=new WeakMap<PartDefinition,FitBounds>();
function cacheBound(cache:WeakMap<PartDefinition,Map<string,FitBounds>>,def:PartDefinition,key:string,compute:()=>FitBounds){let map=cache.get(def);if(!map){map=new Map();cache.set(def,map);}const hit=map.get(key);if(hit)return hit;const value=compute();map.set(key,value);return value;}
export function featureSourceBounds(def:PartDefinition,kind:'eye'|'brow'|'nose'|'mouth'):FitBounds{return cacheBound(featureBoundsCache,def,kind,()=>kind==='eye'?coverageBoundsForPart(def,layer=>layer!=='eye-glint',.998):kind==='mouth'?coverageBoundsForPart(def,layer=>layer!=='mouth-detail',.998):coverageBoundsForPart(def,undefined,.998));}
export function outfitSourceBounds(kind:'hood'|'shirt'|'strap'|'accent',def:PartDefinition):FitBounds{return cacheBound(outfitBoundsCache,def,kind,()=>kind==='hood'?coverageBoundsForPart(def,layer=>layer==='hood',.998):kind==='shirt'?coverageBoundsForPart(def,layer=>layer==='shirt',.998):kind==='strap'?coverageBoundsForPart(def,layer=>layer==='strap',.995):coverageBoundsForPart(def,layer=>layer==='accent',.998));}
function faceSourceBounds(def:PartDefinition){const hit=faceBoundsCache.get(def);if(hit)return hit;const value=coverageBoundsForPart(def,undefined,.999);faceBoundsCache.set(def,value);return value;}
function jacketSourceBounds(def:PartDefinition){const hit=jacketBoundsCache.get(def);if(hit)return hit;const value=coverageBoundsForPart(def,layer=>layer==='jacket',.999);jacketBoundsCache.set(def,value);return value;}
function jacketTorsoSourceBounds(def:PartDefinition){const hit=jacketTorsoCache.get(def);if(hit)return hit;const value=quantileBoundsForPart(def,layer=>layer==='jacket',.18,.82,.02,.98);jacketTorsoCache.set(def,value);return value;}

export function mirrorBoundsX(bounds:FitBounds):FitBounds{return{minX:-bounds.maxX,minY:bounds.minY,maxX:-bounds.minX,maxY:bounds.maxY};}
export function transformPoint([x,y]:Vec2,t:PartTransform):Vec2{const px=x*t.scaleX,py=y*t.scaleY,c=Math.cos(t.rotation),s=Math.sin(t.rotation);return[px*c-py*s+t.x,px*s+py*c+t.y];}
export function transformBounds(bounds:FitBounds,t:PartTransform):FitBounds{const points:Vec2[]=[[bounds.minX,bounds.minY],[bounds.minX,bounds.maxY],[bounds.maxX,bounds.minY],[bounds.maxX,bounds.maxY]];let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const point of points){const[x,y]=transformPoint(point,t);minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}return{minX,minY,maxX,maxY};}
export function jacketTorsoBounds(def:PartDefinition,t:PartTransform):FitBounds{return transformBounds(jacketTorsoSourceBounds(def),t);}
export function fitBoundsToRect(source:FitBounds,target:FitRect,mode:'contain'|'cover'='contain',align:'center'|'top'|'bottom'='center'):PartTransform{const sx=width(target)/width(source),sy=height(target)/height(source),scale=mode==='cover'?Math.max(sx,sy):Math.min(sx,sy),sourceCenter=center(source),targetCenter=center(target);let y=targetCenter[1]-sourceCenter[1]*scale;if(align==='top')y=target.maxY-source.maxY*scale;else if(align==='bottom')y=target.minY-source.minY*scale;return{x:targetCenter[0]-sourceCenter[0]*scale,y,scaleX:scale,scaleY:scale,rotation:0,spacing:0};}
export function composeFit(base:PartTransform,user?:PartTransform):PartTransform{if(!user)return{...base};return{x:base.x+user.x,y:base.y+user.y,scaleX:base.scaleX*user.scaleX,scaleY:base.scaleY*user.scaleY,rotation:base.rotation+user.rotation,spacing:user.spacing??0};}
export function rectFromBounds(bounds:FitBounds,x0:number,y0:number,x1:number,y1:number):FitRect{const w=width(bounds),h=height(bounds);return{minX:bounds.minX+w*x0,minY:bounds.minY+h*y0,maxX:bounds.minX+w*x1,maxY:bounds.minY+h*y1};}

export const LAYER_Z:Readonly<Record<string,number>>=Object.freeze({'skin-base':0,'shirt':2,'jacket-underlay':3,'jacket':4,'accent':6,'hood':7,'strap':8,'strap-metal':9,'hair-back':18,'face':21,'face-outline':22,'eye-outline':30,'eye-white':31,'iris':32,'pupil':33,'eye-glint':34,'nose':35,'mouth-outline':36,'mouth':37,'mouth-detail':38,'brows':40,'hair-front':50,'hair-accent':51});
export function resolvedLayerZ(layer:string,fallback:number):number{return LAYER_Z[layer]??fallback;}

const HAIR_REFERENCE_SEED:Partial<Record<HairStyleId,PartTransform>>={ponytail:{x:.12865,y:-.03616,scaleX:1.32327,scaleY:1.32325,rotation:0},braid:{x:.06740,y:-.02455,scaleX:.98017,scaleY:1.09094,rotation:0},bob:{x:-.23278,y:-.02590,scaleX:1.02921,scaleY:1.11777,rotation:0},'half-up':{x:-.01840,y:-.02024,scaleX:1.00470,scaleY:1.00468,rotation:0},long:{x:-.05513,y:-.02497,scaleX:1.00468,scaleY:1.10002,rotation:0},bun:{x:0,y:-.02332,scaleX:1.06594,scaleY:1.06596,rotation:0},'short-spike':{x:-.08577,y:-.00980,scaleX:.79640,scaleY:.79638,rotation:0},'side-tail':{x:-.04288,y:-.02479,scaleX:.96792,scaleY:1.09543,rotation:0},wavy:{x:-.11028,y:-.01480,scaleX:.77188,scaleY:.89608,rotation:0},'twin-tail':{x:-.01838,y:-.02592,scaleX:.98018,scaleY:1.11862,rotation:0}};
function hairCloud(def:PartDefinition){const xs:number[]=[],ys:number[]=[];for(const triangle of def.triangles)for(const[x,y]of triangle.points){xs.push(x);ys.push(y);}const qx20=quantile(xs,.2),qx50=quantile(xs,.5),qx80=quantile(xs,.8),qy90=quantile(ys,.9),centralY:number[]=[];for(const triangle of def.triangles)for(const[x,y]of triangle.points)if(x>=qx20&&x<=qx80)centralY.push(y);return{qx20,qx50,qx80,qy90,fringe:quantile(centralY.length?centralY:ys,.16)};}
function derivedHairSeed(cloud:ReturnType<typeof hairCloud>,face:FitBounds):PartTransform{const fw=width(face),fh=height(face),fc=center(face),targetWidth=fw*.96,targetHeight=fh*.62,sourceWidth=Math.max(EPS,cloud.qx80-cloud.qx20),sourceHeight=Math.max(EPS,cloud.qy90-cloud.fringe),sx=targetWidth/sourceWidth,sy=targetHeight/sourceHeight,scale=clamp(Math.sqrt(sx*sy),.45,1.8),targetTop=face.maxY+fh*.18;return{x:fc[0]-cloud.qx50*scale,y:targetTop-cloud.qy90*scale,scaleX:scale,scaleY:scale,rotation:0,spacing:0};}
const hairCache=new Map<string,{transform:PartTransform;score:number}>();
export function autoFitHair(id:HairStyleId,def:PartDefinition,face:FitBounds):{transform:PartTransform;score:number}{const key=`${id}:${face.minX.toFixed(3)}:${face.minY.toFixed(3)}:${face.maxX.toFixed(3)}:${face.maxY.toFixed(3)}`;const cached=hairCache.get(key);if(cached)return cached;const cloud=hairCloud(def),fw=width(face),fh=height(face),fc=center(face),targetTop=face.maxY+fh*.18,targetLeft=fc[0]-fw*.48,targetRight=fc[0]+fw*.48,targetFringe=face.minY+fh*.56,bases=[derivedHairSeed(cloud,face),HAIR_REFERENCE_SEED[id]??IDENTITY];let best={transform:{...bases[0]},score:Infinity};for(const seed of bases)for(const scaleMul of[.90,.94,.97,1,1.03,1.06,1.10])for(const dx of[-.08,-.04,0,.04,.08])for(const dy of[-.08,-.04,0,.04,.08]){const transform:PartTransform={x:seed.x+dx*fw,y:seed.y+dy*fh,scaleX:seed.scaleX*scaleMul,scaleY:seed.scaleY*scaleMul,rotation:0,spacing:0},tx=(x:number)=>x*transform.scaleX+transform.x,ty=(y:number)=>y*transform.scaleY+transform.y,left=tx(cloud.qx20),right=tx(cloud.qx80),top=ty(cloud.qy90),fringe=ty(cloud.fringe),mid=tx(cloud.qx50),score=Math.pow((left-targetLeft)/fw,2)+Math.pow((right-targetRight)/fw,2)+3*Math.pow((mid-fc[0])/fw,2)+3*Math.pow((top-targetTop)/fh,2)+2*Math.pow((fringe-targetFringe)/fh,2);if(score<best.score)best={transform,score};}hairCache.set(key,best);return best;}

export const REFERENCE_ANATOMY_TARGETS={eyeLeft:[.045,.335,.395,.615],eyeRight:[.605,.335,.955,.615],browLeft:[.14,.705,.415,.765],browRight:[.55,.705,.825,.765],nose:[.44,.285,.56,.365],mouth:[.365,.095,.655,.25]} as const;
export function autoFitFace(def:PartDefinition,canonical:FitRect):PartTransform{return fitBoundsToRect(faceSourceBounds(def),canonical,'contain','center');}
export function featureTarget(face:FitBounds,kind:'eye'|'brow'|'nose'|'mouth',side:-1|0|1=0):FitRect{const r=kind==='eye'?(side<0?REFERENCE_ANATOMY_TARGETS.eyeLeft:REFERENCE_ANATOMY_TARGETS.eyeRight):kind==='brow'?(side<0?REFERENCE_ANATOMY_TARGETS.browLeft:REFERENCE_ANATOMY_TARGETS.browRight):kind==='nose'?REFERENCE_ANATOMY_TARGETS.nose:REFERENCE_ANATOMY_TARGETS.mouth;return rectFromBounds(face,r[0],r[1],r[2],r[3]);}
export function autoFitFeature(def:PartDefinition,face:FitBounds,kind:'eye'|'brow'|'nose'|'mouth',side:-1|0|1=0):PartTransform{const raw=featureSourceBounds(def,kind),source=side<0?mirrorBoundsX(raw):raw;return fitBoundsToRect(source,featureTarget(face,kind,side),'contain','center');}
export function autoFitJacket(def:PartDefinition,canonicalJacket:FitRect):PartTransform{return fitBoundsToRect(jacketSourceBounds(def),canonicalJacket,'contain','top');}
// Component rectangles are relative to the torso core, not sleeve-to-sleeve outer bounds. This keeps
// harnesses and collars correctly sized across long-sleeve, short-sleeve and vest silhouettes.
export function outfitTarget(kind:'hood'|'shirt'|'strap'|'accent',id:string,torso:FitBounds):FitRect{if(kind==='hood')return rectFromBounds(torso,-.08,.79,1.08,1.11);if(kind==='shirt')return rectFromBounds(torso,-.10,.04,1.10,.92);if(kind==='strap'){const harness=(id as StrapStyleId)==='cross'||(id as StrapStyleId)==='y-harness';return harness?rectFromBounds(torso,-.05,.10,1.05,.87):rectFromBounds(torso,.00,.08,1.00,.91);}const anchor:Record<AccentStyleId,readonly[number,number,number,number]>={diamond:[.35,.48,.65,.68],'long-strip':[.45,.24,.55,.76],'point-strip':[.54,.25,.64,.76],corner:[.62,.55,.92,.76],chevron:[.24,.56,.76,.72],slash:[.60,.38,.84,.56],taper:[.18,.31,.40,.55],triangle:[.36,.42,.64,.59]};const region=anchor[id as AccentStyleId]??([.35,.45,.65,.65] as const);return rectFromBounds(torso,region[0],region[1],region[2],region[3]);}
export function autoFitOutfitComponent(kind:'hood'|'shirt'|'strap'|'accent',id:string,def:PartDefinition,torso:FitBounds):PartTransform{return fitBoundsToRect(outfitSourceBounds(kind,def),outfitTarget(kind,id,torso),'contain','center');}

export function intersectionArea(a:FitBounds,b:FitBounds):number{return Math.max(0,Math.min(a.maxX,b.maxX)-Math.max(a.minX,b.minX))*Math.max(0,Math.min(a.maxY,b.maxY)-Math.max(a.minY,b.minY));}
export function overlapRatio(inner:FitBounds,outer:FitBounds):number{return intersectionArea(inner,outer)/Math.max(width(inner)*height(inner),EPS);}
export function fitAlignmentScore(fitted:FitBounds,target:FitRect):number{const[fx,fy]=center(fitted),[tx,ty]=center(target),tw=width(target),th=height(target),overflow=containmentPenalty(fitted,target,.03),fill=Math.min(width(fitted)/tw,height(fitted)/th);return Math.hypot((fx-tx)/tw,(fy-ty)/th)+overflow+Math.max(0,.18-fill)*2;}
export function fitEntry(id:string,family:string,def:PartDefinition,target:FitRect,transform:PartTransform,score?:number,sourceOverride?:FitBounds):AutoFitEntry{const source=sourceOverride??def.bounds,fitted=transformBounds(source,transform);return{id,family,transform:{...transform},source:{...source},target:{...target},fitted,score:score??fitAlignmentScore(fitted,target)};}
export function containmentPenalty(inner:FitBounds,outer:FitBounds,pad=.08):number{const ow=width(outer),oh=height(outer),expanded={minX:outer.minX-ow*pad,minY:outer.minY-oh*pad,maxX:outer.maxX+ow*pad,maxY:outer.maxY+oh*pad},overflow=Math.max(0,expanded.minX-inner.minX)+Math.max(0,inner.maxX-expanded.maxX)+Math.max(0,expanded.minY-inner.minY)+Math.max(0,inner.maxY-expanded.maxY);return overflow/Math.max(ow+oh,EPS);}
export function clampUserTransform(user:PartTransform):PartTransform{return{x:clamp(user.x,-.5,.5),y:clamp(user.y,-.5,.5),scaleX:clamp(user.scaleX,.45,1.8),scaleY:clamp(user.scaleY,.45,1.8),rotation:clamp(user.rotation,-.7,.7),spacing:clamp(user.spacing??0,-.25,.25)};}
